if: tag IS blank
branches:
  only:
  - master
env:
  global:
  - SWIFT_BRANCH=swift-5.2-release
  - SWIFT_VERSION=swift-5.2-RELEASE
  - CODECOV_TOKEN="d7a367d7-f9fa-4528-ab12-77c079132de8"
  - PACKAGE_VERSION=0.0.1
jobs:
  include:
  - stage: Linux test
    os: linux
    language: generic
    dist: xenial
    sudo: required
    install:
    - sudo apt-get install clang libcurl3 libcurl4-openssl-dev libpython2.7 libpython2.7-dev
      libicu-dev libstdc++6
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1604/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu16.04.tar.gz
      > $SWIFT_VERSION-ubuntu16.04.tar.gz
    - tar xzf $SWIFT_VERSION-ubuntu16.04.tar.gz
    - export PATH="$(pwd)/$SWIFT_VERSION-ubuntu16.04/usr/bin:$PATH"
    script:
    - swift package update
    - swift test
  - stage: OSX test
    os: osx
    osx_image: xcode11.3.1
    language: swift
    sudo: required
    install:
    - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
    - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    script:
    - xcodebuild -scheme CRC test -enableCodeCoverage YES
    after_success:
    - bash <(curl -s https://codecov.io/bash) -X xcodellvm
